### PR TITLE
Monospace text and better color.

### PR DESCRIPTION
**Pull request by mathiasrw**
The text works much better at monospace when reading. 

Also, 100% black and 100% white is not super awesome to read for long time - so it has been tuned.

---
This change is [Reviewable](https://reviewable.io/reviews/kessler/node-bcat/6)

### CODE REVIEW

**Comment by kessler** [comment]
@mathiasrw sorry for the late response, I just tested your branch on my computer and this was the result:

image

Is that the result you meant to have?
Also (and maybe you know this), it's possible to fixate these colors for your bcat via rc file

**Comment by mathiasrw** [comment]
Oh - let me just review that. No - it should be nice and looking good.

**Comment by kessler** [comment]
@mathiasrw bump

**Comment by mathiasrw** [comment]
Sorry about the looooong unneeded waiting time. Ill bump and have a go at this in the weekend.

**Comment by kessler** [comment]
@mathiasrw no worries... :)

**Comment by mathiasrw** [comment]
Ok - working and tested. Not sure why that last changes did not work, but started again. I also added a minimum of info so you dont forget what the tab is about when you have lots of things running. 

image

**Comment by kessler** [comment]
published to npm bcat@1.20

**Pull request merged**
